url: https://domain.com
domain: domain.com
title: Site Title
exclude:
  - "*.config.js"
  - "package*.json"
  - "tailwind"
  - "node_modules"
include:
  - humans.txt
  - admin
defaults:
collections:
  places:
    output: true
    permalink: /places/:name/
include:
  - _redirects
