---
title: The Bath Insider
timezone: UTC
collections:
  places:
    title: Places
    output: true
    permalink: "/places/:name/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://domain.com
domain: domain.com
exclude:
  - "*.config.js"
  - package*.json
  - tailwind
  - node_modules
include:
  - _redirects
